'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Barras
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sistemas_Integrados.Barras", GetType(Barras).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_File_Open_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.File.Open.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_File_PageSetup_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.File.PageSetup.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_File_Print_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.File.Print.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_File_Reflow_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.File.Reflow.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_File_Save_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.File.Save.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Navigation_GoFirst_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Navigation.GoFirst.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Navigation_GoLast_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Navigation.GoLast.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Navigation_GoNext_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Navigation.GoNext.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Navigation_GoPrev_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Navigation.GoPrev.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Navigation_HistoryNext_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Navigation.HistoryNext.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Navigation_HistoryPrev_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Navigation.HistoryPrev.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Page_Continuous_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Page.Continuous.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Page_Facing_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Page.Facing.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Page_FacingContinuous_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Page.FacingContinuous.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Page_Single_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Page.Single.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Text_Hand_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Text.Hand.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Zoom_ZoomIn_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Zoom.ZoomIn.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Zoom_ZoomOut_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Zoom.ZoomOut.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property C1PrintPreviewControl1_ToolBars_Zoom_ZoomTool_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("C1PrintPreviewControl1.ToolBars.Zoom.ZoomTool.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;!--Report *** Unnamed Report ***--&gt;&lt;Report version=&quot;2.6.20132.54642&quot;&gt;&lt;ReportInfo /&gt;&lt;DataSource&gt;&lt;DataProvider&gt;0&lt;/DataProvider&gt;&lt;/DataSource&gt;&lt;Layout /&gt;&lt;Font&gt;&lt;Name&gt;Arial&lt;/Name&gt;&lt;Size&gt;9&lt;/Size&gt;&lt;/Font&gt;&lt;CompatibilityOptions /&gt;&lt;Groups /&gt;&lt;Sections&gt;&lt;Section&gt;&lt;Name&gt;Detail&lt;/Name&gt;&lt;Type&gt;0&lt;/Type&gt;&lt;Visible&gt;0&lt;/Visible&gt;&lt;/Section&gt;&lt;Section&gt;&lt;Name&gt;Header&lt;/Name&gt;&lt;Type&gt;1&lt;/Type&gt;&lt;Visible&gt;0&lt;/Visible&gt;&lt;/Section&gt;&lt;Section&gt;&lt;Name&gt;Footer&lt;/Name&gt;&lt;Type&gt;2&lt;/Type&gt;&lt;Visible&gt;0&lt;/Visible&gt;&lt;/Section&gt;&lt;Section&gt;&lt;Name&gt;PageHeader&lt;/Name&gt;&lt;Type&gt;3&lt;/Type&gt;&lt;Visible&gt;0&lt;/ [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property c1r_ReportDefinition() As String
        Get
            Return ResourceManager.GetString("c1r.ReportDefinition", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property c1r_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("c1r.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property impri_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("impri.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property regresa_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("regresa.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
